// src/pages/Reports.jsx
import { useState } from 'react';
import { FileText, Download, Zap } from 'lucide-react';
import api from '../utils/api';
import toast from 'react-hot-toast';

export default function Reports() {
  const [patientId, setPatientId] = useState('');
  const [report, setReport]       = useState(null);
  const [loading, setLoading]     = useState(false);
  const [patient, setPatient]     = useState(null);

  const generateReport = async () => {
    if (!patientId) { toast.error('Enter a patient ID'); return; }
    setLoading(true);
    try {
      const res = await api.post(`/ai/report/${patientId}`);
      setReport(res.data.report);
      setPatient(res.data.patient);
      toast.success('Report generated!');
    } catch (e) { toast.error(e.response?.data?.error || 'Failed to generate report'); }
    finally { setLoading(false); }
  };

  const downloadReport = () => {
    const content = `NEUROQ AI MEDICAL REPORT
${'='.repeat(50)}
Patient: ${patient?.full_name} (${patient?.patient_code})
Age: ${patient?.age} | Gender: ${patient?.gender}
Date: ${new Date().toLocaleDateString('en-IN', {day:'numeric',month:'long',year:'numeric'})}
${'='.repeat(50)}

${report}

${'='.repeat(50)}
Generated by NeuroQ AI v2.0
Disclaimer: This report is AI-generated and should be reviewed by a qualified physician.`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = `NeuroQ_Report_${patient?.patient_code}_${Date.now()}.txt`;
    a.click(); URL.revokeObjectURL(url);
    toast.success('Report downloaded!');
  };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-100">Medical Report Generator</h1>
        <p className="text-sm text-slate-500 mt-1">AI-generated clinical reports powered by Mistral-7B</p>
      </div>

      <div className="bg-[#0d1526] border border-cyan-900/20 rounded-xl p-5 mb-5">
        <div className="flex gap-3">
          <input value={patientId} onChange={e=>setPatientId(e.target.value)}
            placeholder="Enter Patient ID (1–8 for demo)"
            className="flex-1 bg-[#0a0f1e] border border-cyan-900/30 rounded-xl px-4 py-2.5 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:border-cyan-500/50" />
          <button onClick={generateReport} disabled={loading}
            className="flex items-center gap-2 px-6 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-xl text-sm font-semibold disabled:opacity-50 transition-all">
            <Zap size={14} className={loading?'animate-spin':''}/>
            {loading ? 'Generating…' : 'Generate Report'}
          </button>
        </div>
      </div>

      {report && (
        <div className="bg-[#0d1526] border border-cyan-900/20 rounded-xl overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-cyan-900/20">
            <div className="flex items-center gap-3">
              <FileText size={18} className="text-cyan-400"/>
              <div>
                <div className="text-sm font-semibold text-slate-200">{patient?.full_name}</div>
                <div className="text-xs text-slate-500">{patient?.patient_code} · {new Date().toLocaleDateString('en-IN')}</div>
              </div>
            </div>
            <button onClick={downloadReport}
              className="flex items-center gap-2 px-4 py-2 bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 rounded-xl text-sm hover:bg-cyan-500/20 transition-all">
              <Download size={14}/> Download
            </button>
          </div>
          <div className="p-6">
            <pre className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">{report}</pre>
          </div>
          <div className="px-6 py-3 border-t border-cyan-900/20 bg-yellow-500/5">
            <p className="text-xs text-yellow-400/70">⚠ Disclaimer: This AI-generated report is for clinical assistance only and must be reviewed by a qualified physician.</p>
          </div>
        </div>
      )}
    </div>
  );
}
